--------------------------------------------------------------------------------------------------
-- Table: public.tipocuenta

DROP TABLE public.cuenta;
DROP TABLE public.cliente;
DROP TABLE public.banco;
DROP TABLE public.usuarios;
DROP TABLE public.tipocuenta;

CREATE TABLE public.tipocuenta
(
    id_tipocuenta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 4 CACHE 1 ),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipocuenta_pkey PRIMARY KEY (id_tipocuenta),
    CONSTRAINT tipocuenta_nombre_key UNIQUE (nombre)
)

TABLESPACE pg_default;

ALTER TABLE public.tipocuenta
    OWNER to postgres; 
	
--------------------------------------------------------------------------------------------------
-- Table: public.usuarios



CREATE TABLE public.usuarios
(
    id_usuario integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    usuario text COLLATE pg_catalog."default" NOT NULL,
    tipo_usuario integer NOT NULL,
    contrasena text NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
)

TABLESPACE pg_default;

ALTER TABLE public.usuarios
    OWNER to postgres; 

----------------------------------------------------------------------------------------------------
-- Table: public.banco



CREATE TABLE public.banco
(
    id_banco integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    numero_sucursal text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT banco_pkey PRIMARY KEY (id_banco),
    CONSTRAINT banco_numerosucursal_key UNIQUE (numero_sucursal)
)

TABLESPACE pg_default;

ALTER TABLE public.banco
    OWNER to postgres;
--------------------------------------------------------------------------------------------------



-- Table: public.cliente



CREATE TABLE public.cliente
(
    id_cliente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    nombre_apellido text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    telefono text COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date NOT NULL,
    dni text COLLATE pg_catalog."default" NOT NULL,
    cuit_cuil text COLLATE pg_catalog."default" NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT cliente_cuit_cuil_key UNIQUE (cuit_cuil),
    CONSTRAINT cliente_dni_key UNIQUE (dni),
    CONSTRAINT usuario FOREIGN KEY (id_usuario)
        REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.cliente
    OWNER to postgres; 
--------------------------------------------------------------------------------------------------


-- Table: public.cuenta



CREATE TABLE public.cuenta
(
    id_cuenta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    numero text COLLATE pg_catalog."default" NOT NULL,
    tipo_cuenta integer NOT NULL,
    fecha_start date NOT NULL,
    tipo_moneda text COLLATE pg_catalog."default" NOT NULL,
    monto integer NOT NULL,
    id_titular integer NOT NULL,
    id_banco integer NOT NULL,
    CONSTRAINT cuenta_pkey PRIMARY KEY (id_cuenta),
    CONSTRAINT cuenta_numero_key UNIQUE (numero),
    CONSTRAINT banco FOREIGN KEY (id_banco)
        REFERENCES public.banco (id_banco) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "tipoCuenta" FOREIGN KEY (tipo_cuenta)
        REFERENCES public.tipocuenta (id_tipocuenta) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT titular FOREIGN KEY (id_titular)
        REFERENCES public.cliente (id_cliente) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.cuenta
    OWNER to postgres; 


INSERT INTO tipocuenta(nombre) values ('Caja de Ahorros');
INSERT INTO tipocuenta(nombre) values ('Cuenta Sueldo / Cuenta de Seguridad Social');
INSERT INTO tipocuenta(nombre) values ('Cuenta Corriente');
INSERT INTO tipocuenta(nombre) values ('Cuenta Universal Gratuita');